Portable Compute Language: poclu/bswap.c File Reference
bswap.c File Reference
byte swap functions
#include "pocl_opencl.h"
Macros
#define GENERIC_BYTESWAP(__DTYPE, __WORD)
inplace endian byte swap macro
Functions
static int needs_swap (cl_device_id device)
internal function to compare device- to host-endianness.
cl_int poclu_bswap_cl_int (cl_device_id device, cl_int original)
Byte swap functions for endianness swapping between the host (current CPU) and a target device.
cl_half poclu_bswap_cl_half (cl_device_id device, cl_half original)
Byte swap functions for endianness swapping between the host (current CPU) and a target device.
cl_float poclu_bswap_cl_float (cl_device_id device, cl_float original)
Byte swap functions for endianness swapping between the host (current CPU) and a target device.
void poclu_bswap_cl_int_array (cl_device_id device, cl_int *array, size_t num_elements)
Byte swap functions for endianness swapping between the host (current CPU) and a target device.
void poclu_bswap_cl_half_array (cl_device_id device, cl_half *array, size_t num_elements)
Byte swap functions for endianness swapping between the host (current CPU) and a target device.
void poclu_bswap_cl_float_array (cl_device_id device, cl_float *array, size_t num_elements)
Byte swap functions for endianness swapping between the host (current CPU) and a target device.
void poclu_bswap_cl_float2_array (cl_device_id device, cl_float2 *array, size_t num_elements)
Byte swap functions for endianness swapping between the host (current CPU) and a target device.
Detailed Description
byte swap functions
Copyright (c) 2012 Pekka Jääskeläinen / Tampere University of Technology
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Macro Definition Documentation
GENERIC_BYTESWAP
#define GENERIC_BYTESWAP (__DTYPE, __WORD)
Value:
  do {                                                            \
    unsigned __i;                                                 \
    union _word_union                                             \
    {                                                             \
      __DTYPE full_word;                                          \
      unsigned char bytes[sizeof(__DTYPE)];                       \
    } __old, __neww;                                              \
                                                                  \
    __old.full_word = __WORD;                                     \
    for (__i = 0; __i < sizeof(__DTYPE); ++__i)                   \
      __neww.bytes[__i] = __old.bytes[sizeof(__DTYPE) - __i - 1]; \
    __WORD = __neww.full_word;                                    \
  } while(0)
inplace endian byte swap macro
Parameters
__DTYPE [in] word datatype
__WORD [in/out] data to be swapped in place
Function Documentation
needs_swap()
static int needs_swap (cl_device_id device) static
internal function to compare device- to host-endianness.
Parameters
device [in] device in question
Returns
1 if endianness is not the same.
Referenced by poclu_bswap_cl_float(), poclu_bswap_cl_float2_array(), poclu_bswap_cl_float_array(), poclu_bswap_cl_half(), poclu_bswap_cl_half_array(), poclu_bswap_cl_int(), and poclu_bswap_cl_int_array().
poclu_bswap_cl_float()
cl_float poclu_bswap_cl_float (cl_device_id device, cl_float original)
Byte swap functions for endianness swapping between the host (current CPU) and a target device.
Queries the target device using the OpenCL API for the endianness and swaps if it differs from the host's.
Parameters
[in] device the device id of the target
[in] original the input to potentially swapped
Returns
the input in the correct endianness.
poclu_bswap_cl_float2_array()
void poclu_bswap_cl_float2_array (cl_device_id device, cl_float2 * array, size_t num_elements)
Byte swap functions for endianness swapping between the host (current CPU) and a target device.
Queries the target device using the OpenCL API for the endianness and swaps if it differs from the host's.
Parameters
[in] device the device id of the target
[in] array array pointer to elements to be potentially swapped
[in] num_elements number of elements in the array
Returns
the input in the correct endianness
poclu_bswap_cl_float_array()
void poclu_bswap_cl_float_array (cl_device_id device, cl_float * array, size_t num_elements)
Byte swap functions for endianness swapping between the host (current CPU) and a target device.
Queries the target device using the OpenCL API for the endianness and swaps if it differs from the host's.
Parameters
[in] device the device id of the target
[in] array array pointer to elements to be potentially swapped
[in] num_elements number of elements in the array
Returns
the input in the correct endianness
poclu_bswap_cl_half()
cl_half poclu_bswap_cl_half (cl_device_id device, cl_half original)
Byte swap functions for endianness swapping between the host (current CPU) and a target device.
Queries the target device using the OpenCL API for the endianness and swaps if it differs from the host's.
Parameters
[in] device the device id of the target
[in] original the input to potentially swapped
Returns
the input in the correct endianness.
poclu_bswap_cl_half_array()
void poclu_bswap_cl_half_array (cl_device_id device, cl_half * array, size_t num_elements)
Byte swap functions for endianness swapping between the host (current CPU) and a target device.
Queries the target device using the OpenCL API for the endianness and swaps if it differs from the host's.
Parameters
[in] device the device id of the target
[in] array array pointer to elements to be potentially swapped
[in] num_elements number of elements in the array
Returns
the input in the correct endianness
poclu_bswap_cl_int()
cl_int poclu_bswap_cl_int (cl_device_id device, cl_int original)
Byte swap functions for endianness swapping between the host (current CPU) and a target device.
Queries the target device using the OpenCL API for the endianness and swaps if it differs from the host's.
Parameters
[in] device the device id of the target
[in] original the input to potentially swapped
Returns
the input in the correct endianness.
poclu_bswap_cl_int_array()
void poclu_bswap_cl_int_array (cl_device_id device, cl_int * array, size_t num_elements)
Byte swap functions for endianness swapping between the host (current CPU) and a target device.
Queries the target device using the OpenCL API for the endianness and swaps if it differs from the host's.
Parameters
[in] device the device id of the target
[in] array array pointer to elements to be potentially swapped
[in] num_elements number of elements in the array
Returns
the input in the correct endianness