Portable Compute Language: poclu/misc.c File Reference
misc.c File Reference
poclu_misc - misc generic OpenCL helper functions
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include "config.h"
#include "pocl_opencl.h"
Macros
#define OPENCL_ERROR_CASE(ERR)
private macro to check errors in check_cl_error function
Functions
cl_context poclu_create_any_context ()
Create a context in the first platform found.
cl_int poclu_get_any_device (cl_context *context, cl_device_id *device, cl_command_queue *queue)
set up a context, device and queue for platform 0, device 0.
cl_int poclu_get_any_device2 (cl_context *context, cl_device_id *device, cl_command_queue *queue, cl_platform_id *platform)
Set up a context, device and queue for platform 0, device 0.
cl_int poclu_get_multiple_devices (cl_platform_id *platform, cl_context *context, cl_uint *num_devices, cl_device_id **devices, cl_command_queue **queues)
set up all available devices and queues for a single context on the first platform.
char * poclu_read_binfile (const char *filename, size_t *len)
read the contents of a file.
char * poclu_read_file (const char *filename)
read the contents of a file.
int poclu_write_file (const char *filename, char *content, size_t size)
write content to a file.
cl_int poclu_show_program_build_log (cl_program program)
print program build log of each device to stderr.
int check_cl_error (cl_int cl_err, int line, const char *func_name)
check a return value of CL function or print the error to stderr.
static int pocl_getpath (char *path, size_t len, const char *explicit_binary, const char *basename, const char *ext)
get the path of a source file.
int poclu_load_program_multidev (cl_context context, cl_device_id *devices, cl_uint num_devices, const char *basename, int spir, int spirv, int poclbin, const char *explicit_binary, const char *extra_build_opts, cl_program *p)
create a program from different sources
int poclu_load_program (cl_context context, cl_device_id device, const char *basename, int spir, int spirv, int poclbin, const char *explicit_binary, const char *extra_build_opts, cl_program *p)
wrapper for poclu_load_program_multidev, see it for details.
Detailed Description
poclu_misc - misc generic OpenCL helper functions
Copyright (c) 2013 Pekka Jääskeläinen / Tampere University of Technology Copyright (c) 2014 Kalle Raiskila
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Macro Definition Documentation
OPENCL_ERROR_CASE
#define OPENCL_ERROR_CASE (ERR)
Value:
  case ERR:                                                             \
  { fprintf (stderr, "" #ERR " in %s on line %i\n", func_name, line);   \
    return 1; }
private macro to check errors in check_cl_error function
Function Documentation
check_cl_error()
int check_cl_error (cl_int cl_err, int line, const char * func_name)
check a return value of CL function or print the error to stderr.
Parameters
cl_err [in] value to be checked.
line [in] line of function in question.
func_name [in] name of the function in question.
Returns
0 if cl_err is CL_SUCCESS otherwise 1.
Referenced by poclu_show_program_build_log().
pocl_getpath()
static int pocl_getpath (char * path, size_t len, const char * explicit_binary, const char * basename, const char * ext) static
get the path of a source file.
can be either used by passing the explicit_binary option or using basename + ext arguments. if basename + ext is not found in current working directory, it will check the build or source directories for said file.
Parameters
path [out] the return string of the path.
len [in] the lenght of the destination path.
explicit_binary [in] string to the file.
basename [in] relative name of the program c program running.
ext [in] extension of the file.
Returns
CL_SUCCESS or CL_BUILD_PROGRAM_FAILURE on error.
Referenced by poclu_load_program_multidev().
poclu_create_any_context()
cl_context poclu_create_any_context ()
Create a context in the first platform found.
Misc. helper functions for streamlining OpenCL API usage.
Returns
a cl_context.
poclu_get_any_device()
cl_int poclu_get_any_device (cl_context * context, cl_device_id * device, cl_command_queue * queue)
set up a context, device and queue for platform 0, device 0.
similar to pocl_get_any_device2, but doesn't return the platform.
Parameters
context [out]
device [out]
queue [out]
Returns
CL_SUCCESS on success, or a descriptive OpenCL error code upon failure.
Warning
All input parameters must be allocated by caller!
poclu_get_any_device2()
cl_int poclu_get_any_device2 (cl_context * context, cl_device_id * device, cl_command_queue * queue, cl_platform_id * platform)
Set up a context, device and queue for platform 0, device 0.
similar to pocl_get_any_device, but returns the platform as well.
Warning
All input parameters must be allocated by caller!
Parameters
context [out]
device [out]
queue [out]
platform [out]
Returns
CL_SUCCESS on success, or a descriptive OpenCL error code upon failure.
Referenced by poclu_get_any_device().
poclu_get_multiple_devices()
cl_int poclu_get_multiple_devices (cl_platform_id * platform, cl_context * context, cl_uint * num_devices, cl_device_id ** devices, cl_command_queue ** queues)
set up all available devices and queues for a single context on the first platform.
Parameters
platform [out] pointer to the first platform found.
context [out] pointer to the shared context of all devices.
num_devices [out] the number of devices found.
devices [out] pointer to array of device pointers.
queues [out] pointer to array of queue pointers.
Returns
CL_SUCCESS on success, or a descriptive OpenCL error code upon failure.
poclu_load_program_multidev()
int poclu_load_program_multidev (cl_context context, cl_device_id * devices, cl_uint num_devices, const char * basename, int spir, int spirv, int poclbin, const char * explicit_binary, const char * extra_build_opts, cl_program * p)
create a program from different sources
this function can create a program from a wide variety of sources, including: spir, spirv, cl or poclbin. It will look for a file with a name matching basename + source type in the following order of directories: current, build and source. If the explicit_binary option is given, it will use that instead. NOTE that the file extension needs to be included in the explicit_binary option.
Parameters
context [in] context where the program should run
devices [in] array of SAME devices for program to run on
num_devices [in] number of devices in array of devices.
basename [in] name of the program to be run, used to find sources.
spir [in] boolean to indicate whether to use spir sources.
spirv [in] boolean to indicate whether to use spirv sources.
poclbin [in] boolean to indicate whether to use a pocl binary source.
explicit_binary [in] optional explicit path to sources.
extra_build_opts [in] string of extra options to use when compiling sources.
p [out] resulting program from source.
Returns
CL_SUCCESS or else a related CL error.
Warning
all devices need to be of the same type or else an error will be thrown.
Referenced by poclu_load_program().
poclu_read_binfile()
char* poclu_read_binfile (const char * filename, size_t * len)
read the contents of a file.
filename can absolute or relative, according to the fopen implementation.
Parameters
filename [in] string to the file.
len [out] length of the binary file.
Returns
a malloc'd buffer pointer or NULL on errors.
Referenced by poclu_load_program_multidev(), and poclu_read_file().
poclu_read_file()
char* poclu_read_file (const char * filename)
read the contents of a file.
filename can absolute or relative, according to the fopen implementation.
Parameters
filename [in] string to the file.
Returns
a malloc'd buffer pointer or NULL on errors.
Referenced by poclu_load_program_multidev().
poclu_show_program_build_log()
cl_int poclu_show_program_build_log (cl_program program)
print program build log of each device to stderr.
Parameters
program [in] program of which to print build logs.
Returns
CL_SUCCESS or else a CL related error.
poclu_write_file()
int poclu_write_file (const char * filename, char * content, size_t size)
write content to a file.
filename can absolute or relative, according to the fopen implementation on system.
Parameters
filename [in] string to the file.
content [in] string to be written.
size [in] size of the content.
Returns
-1 if there is any error otherwise 0.