Portable Compute Language: poclu/poclu.h File Reference
poclu.h File Reference
OpenCL runtime library: poclu - useful utility functions for OpenCL programs.
#include "pocl_opencl.h"
Macros
#define POCLU_CALL
#define POCLU_API
#define _POCLU_CHECK_CL_ERROR_INNER(cond, func, line)
private macro to check error code and return EXIT_FAILURE on error
#define CHECK_CL_ERROR(cond) _POCLU_CHECK_CL_ERROR_INNER(cond, __PRETTY_FUNCTION__, __LINE__)
check a CL return value and if it is an error: print it and exit function on failure
#define CHECK_OPENCL_ERROR_IN(message) _POCLU_CHECK_CL_ERROR_INNER(err, message, __LINE__)
check a CL return value and if it is an error: print the message and exit function on failure.
#define TEST_ASSERT(EXP)
check an expression and if false: print to stderr and exit of failure
#define CHECK_CL_ERROR2(err)
check CL return value and print to stderr and jump to ERROR statement on failure
Functions
POCLU_API cl_int POCLU_CALL poclu_bswap_cl_int (cl_device_id device, cl_int original)
Byte swap functions for endianness swapping between the host (current CPU) and a target device.
POCLU_API cl_half POCLU_CALL poclu_bswap_cl_half (cl_device_id device, cl_half original)
Byte swap functions for endianness swapping between the host (current CPU) and a target device.
POCLU_API cl_float POCLU_CALL poclu_bswap_cl_float (cl_device_id device, cl_float original)
Byte swap functions for endianness swapping between the host (current CPU) and a target device.
POCLU_API cl_float2 POCLU_CALL poclu_bswap_cl_float2 (cl_device_id device, cl_float2 original)
Byte swap functions for endianness swapping between the host (current CPU) and a target device.
POCLU_API void POCLU_CALL poclu_bswap_cl_int_array (cl_device_id device, cl_int *array, size_t num_elements)
Byte swap functions for endianness swapping between the host (current CPU) and a target device.
POCLU_API void POCLU_CALL poclu_bswap_cl_half_array (cl_device_id device, cl_half *array, size_t num_elements)
Byte swap functions for endianness swapping between the host (current CPU) and a target device.
POCLU_API void POCLU_CALL poclu_bswap_cl_float_array (cl_device_id device, cl_float *array, size_t num_elements)
Byte swap functions for endianness swapping between the host (current CPU) and a target device.
POCLU_API void POCLU_CALL poclu_bswap_cl_float2_array (cl_device_id device, cl_float2 *array, size_t num_elements)
Byte swap functions for endianness swapping between the host (current CPU) and a target device.
POCLU_API cl_context POCLU_CALL poclu_create_any_context ()
Create a context in the first platform found.
POCLU_API cl_int POCLU_CALL poclu_get_any_device2 (cl_context *context, cl_device_id *device, cl_command_queue *queue, cl_platform_id *platform)
Set up a context, device and queue for platform 0, device 0.
POCLU_API cl_int POCLU_CALL poclu_get_any_device (cl_context *context, cl_device_id *device, cl_command_queue *queue)
set up a context, device and queue for platform 0, device 0.
POCLU_API cl_int POCLU_CALL poclu_get_multiple_devices (cl_platform_id *platform, cl_context *context, cl_uint *num_devices, cl_device_id **devices, cl_command_queue **queues)
set up all available devices and queues for a single context on the first platform.
POCLU_API cl_half POCLU_CALL poclu_float_to_cl_half (float value)
convert a float to a cl_half (uint16_t).
POCLU_API float POCLU_CALL poclu_cl_half_to_float (cl_half value)
convert a cl_half to a float.
POCLU_API char *POCLU_CALL poclu_read_file (const char *filename)
read the contents of a file.
POCLU_API char *POCLU_CALL poclu_read_binfile (const char *filename, size_t *len)
read the contents of a file.
POCLU_API int POCLU_CALL poclu_write_file (const char *filename, char *content, size_t size)
write content to a file.
int poclu_load_program (cl_context context, cl_device_id device, const char *basename, int spir, int spirv, int poclbin, const char *explicit_binary, const char *extra_build_opts, cl_program *p)
wrapper for poclu_load_program_multidev, see it for details.
int poclu_load_program_multidev (cl_context context, cl_device_id *devices, cl_uint num_devices, const char *basename, int spir, int spirv, int poclbin, const char *explicit_binary, const char *extra_build_opts, cl_program *p)
create a program from different sources
POCLU_API cl_int POCLU_CALL poclu_show_program_build_log (cl_program program)
print program build log of each device to stderr.
POCLU_API int POCLU_CALL check_cl_error (cl_int cl_err, int line, const char *func_name)
check a return value of CL function or print the error to stderr.
Detailed Description
OpenCL runtime library: poclu - useful utility functions for OpenCL programs.
Copyright (c) 2012 Pekka Jääskeläinen / Tampere University of Technology
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Macro Definition Documentation
_POCLU_CHECK_CL_ERROR_INNER
#define _POCLU_CHECK_CL_ERROR_INNER (cond, func, line)
Value:
  do                                                                          \
    {                                                                         \
      if (check_cl_error (cond, line, func))                                  \
        return (EXIT_FAILURE);                                                \
    }                                                                         \
  while (0)
private macro to check error code and return EXIT_FAILURE on error
CHECK_CL_ERROR
#define CHECK_CL_ERROR (cond) _POCLU_CHECK_CL_ERROR_INNER(cond, __PRETTY_FUNCTION__, __LINE__)
check a CL return value and if it is an error: print it and exit function on failure
Parameters
cond [in] cl_int value to check.
CHECK_CL_ERROR2
#define CHECK_CL_ERROR2 (err)
Value:
  if (check_cl_error (err, __LINE__, __PRETTY_FUNCTION__))                    \
  goto ERROR
check CL return value and print to stderr and jump to ERROR statement on failure
Warning
macro assumes "ERROR" statement exists
CHECK_OPENCL_ERROR_IN
#define CHECK_OPENCL_ERROR_IN (message) _POCLU_CHECK_CL_ERROR_INNER(err, message, __LINE__)
check a CL return value and if it is an error: print the message and exit function on failure.
Parameters
message [in] string to print when error is unknown.
Warning
macro assumes CL return value is called "err"
TEST_ASSERT
#define TEST_ASSERT (EXP)
Value:
do {                                                                    \
  if (!(EXP)) {                                                         \
    fprintf(stderr, "Assertion: \n" #EXP "\nfailed on %s:%i\n",         \
        __FILE__, __LINE__);                                            \
    return EXIT_FAILURE;                                                \
  }                                                                     \
} while (0)
check an expression and if false: print to stderr and exit of failure
Parameters
EXP [in]
Function Documentation
check_cl_error()
POCLU_API int POCLU_CALL check_cl_error (cl_int cl_err, int line, const char * func_name)
check a return value of CL function or print the error to stderr.
Parameters
cl_err [in] value to be checked.
line [in] line of function in question.
func_name [in] name of the function in question.
Returns
0 if cl_err is CL_SUCCESS otherwise 1.
Referenced by poclu_show_program_build_log().
poclu_bswap_cl_float()
POCLU_API cl_float POCLU_CALL poclu_bswap_cl_float (cl_device_id device, cl_float original)
Byte swap functions for endianness swapping between the host (current CPU) and a target device.
Queries the target device using the OpenCL API for the endianness and swaps if it differs from the host's.
Parameters
[in] device the device id of the target
[in] original the input to potentially swapped
Returns
the input in the correct endianness.
poclu_bswap_cl_float2()
POCLU_API cl_float2 POCLU_CALL poclu_bswap_cl_float2 (cl_device_id device, cl_float2 original)
Byte swap functions for endianness swapping between the host (current CPU) and a target device.
Queries the target device using the OpenCL API for the endianness and swaps if it differs from the host's.
Parameters
[in] device the device id of the target
[in] original the input to potentially swapped
Returns
the input in the correct endianness.
poclu_bswap_cl_float2_array()
POCLU_API void POCLU_CALL poclu_bswap_cl_float2_array (cl_device_id device, cl_float2 * array, size_t num_elements)
Byte swap functions for endianness swapping between the host (current CPU) and a target device.
Queries the target device using the OpenCL API for the endianness and swaps if it differs from the host's.
Parameters
[in] device the device id of the target
[in] array array pointer to elements to be potentially swapped
[in] num_elements number of elements in the array
Returns
the input in the correct endianness
poclu_bswap_cl_float_array()
POCLU_API void POCLU_CALL poclu_bswap_cl_float_array (cl_device_id device, cl_float * array, size_t num_elements)
Byte swap functions for endianness swapping between the host (current CPU) and a target device.
Queries the target device using the OpenCL API for the endianness and swaps if it differs from the host's.
Parameters
[in] device the device id of the target
[in] array array pointer to elements to be potentially swapped
[in] num_elements number of elements in the array
Returns
the input in the correct endianness
poclu_bswap_cl_half()
POCLU_API cl_half POCLU_CALL poclu_bswap_cl_half (cl_device_id device, cl_half original)
Byte swap functions for endianness swapping between the host (current CPU) and a target device.
Queries the target device using the OpenCL API for the endianness and swaps if it differs from the host's.
Parameters
[in] device the device id of the target
[in] original the input to potentially swapped
Returns
the input in the correct endianness.
poclu_bswap_cl_half_array()
POCLU_API void POCLU_CALL poclu_bswap_cl_half_array (cl_device_id device, cl_half * array, size_t num_elements)
Byte swap functions for endianness swapping between the host (current CPU) and a target device.
Queries the target device using the OpenCL API for the endianness and swaps if it differs from the host's.
Parameters
[in] device the device id of the target
[in] array array pointer to elements to be potentially swapped
[in] num_elements number of elements in the array
Returns
the input in the correct endianness
poclu_bswap_cl_int()
POCLU_API cl_int POCLU_CALL poclu_bswap_cl_int (cl_device_id device, cl_int original)
Byte swap functions for endianness swapping between the host (current CPU) and a target device.
Queries the target device using the OpenCL API for the endianness and swaps if it differs from the host's.
Parameters
[in] device the device id of the target
[in] original the input to potentially swapped
Returns
the input in the correct endianness.
poclu_bswap_cl_int_array()
POCLU_API void POCLU_CALL poclu_bswap_cl_int_array (cl_device_id device, cl_int * array, size_t num_elements)
Byte swap functions for endianness swapping between the host (current CPU) and a target device.
Queries the target device using the OpenCL API for the endianness and swaps if it differs from the host's.
Parameters
[in] device the device id of the target
[in] array array pointer to elements to be potentially swapped
[in] num_elements number of elements in the array
Returns
the input in the correct endianness
poclu_cl_half_to_float()
POCLU_API float POCLU_CALL poclu_cl_half_to_float (cl_half value)
convert a cl_half to a float.
Parameters
value [in] cl_half to be converted.
Returns
a converted float.
poclu_create_any_context()
POCLU_API cl_context POCLU_CALL poclu_create_any_context ()
Create a context in the first platform found.
Misc. helper functions for streamlining OpenCL API usage.
Returns
a cl_context.
poclu_float_to_cl_half()
POCLU_API cl_half POCLU_CALL poclu_float_to_cl_half (float value)
convert a float to a cl_half (uint16_t).
The idea behind these float to half functions is from: https://gamedev.stackexchange.com/a/17410
Parameters
value [in] float to be converted.
Returns
a converted cl_half.
Todo:
not exposed via poclu.h should it be added or removed?
poclu_get_any_device()
POCLU_API cl_int POCLU_CALL poclu_get_any_device (cl_context * context, cl_device_id * device, cl_command_queue * queue)
set up a context, device and queue for platform 0, device 0.
similar to pocl_get_any_device2, but doesn't return the platform.
Parameters
context [out]
device [out]
queue [out]
Returns
CL_SUCCESS on success, or a descriptive OpenCL error code upon failure.
Warning
All input parameters must be allocated by caller!
poclu_get_any_device2()
POCLU_API cl_int POCLU_CALL poclu_get_any_device2 (cl_context * context, cl_device_id * device, cl_command_queue * queue, cl_platform_id * platform)
Set up a context, device and queue for platform 0, device 0.
similar to pocl_get_any_device, but returns the platform as well.
Warning
All input parameters must be allocated by caller!
Parameters
context [out]
device [out]
queue [out]
platform [out]
Returns
CL_SUCCESS on success, or a descriptive OpenCL error code upon failure.
Referenced by poclu_get_any_device().
poclu_get_multiple_devices()
POCLU_API cl_int POCLU_CALL poclu_get_multiple_devices (cl_platform_id * platform, cl_context * context, cl_uint * num_devices, cl_device_id ** devices, cl_command_queue ** queues)
set up all available devices and queues for a single context on the first platform.
Parameters
platform [out] pointer to the first platform found.
context [out] pointer to the shared context of all devices.
num_devices [out] the number of devices found.
devices [out] pointer to array of device pointers.
queues [out] pointer to array of queue pointers.
Returns
CL_SUCCESS on success, or a descriptive OpenCL error code upon failure.
poclu_load_program_multidev()
int poclu_load_program_multidev (cl_context context, cl_device_id * devices, cl_uint num_devices, const char * basename, int spir, int spirv, int poclbin, const char * explicit_binary, const char * extra_build_opts, cl_program * p)
create a program from different sources
this function can create a program from a wide variety of sources, including: spir, spirv, cl or poclbin. It will look for a file with a name matching basename + source type in the following order of directories: current, build and source. If the explicit_binary option is given, it will use that instead. NOTE that the file extension needs to be included in the explicit_binary option.
Parameters
context [in] context where the program should run
devices [in] array of SAME devices for program to run on
num_devices [in] number of devices in array of devices.
basename [in] name of the program to be run, used to find sources.
spir [in] boolean to indicate whether to use spir sources.
spirv [in] boolean to indicate whether to use spirv sources.
poclbin [in] boolean to indicate whether to use a pocl binary source.
explicit_binary [in] optional explicit path to sources.
extra_build_opts [in] string of extra options to use when compiling sources.
p [out] resulting program from source.
Returns
CL_SUCCESS or else a related CL error.
Warning
all devices need to be of the same type or else an error will be thrown.
Referenced by poclu_load_program().
poclu_read_binfile()
POCLU_API char* POCLU_CALL poclu_read_binfile (const char * filename, size_t * len)
read the contents of a file.
filename can absolute or relative, according to the fopen implementation.
Parameters
filename [in] string to the file.
len [out] length of the binary file.
Returns
a malloc'd buffer pointer or NULL on errors.
Referenced by poclu_load_program_multidev(), and poclu_read_file().
poclu_read_file()
POCLU_API char* POCLU_CALL poclu_read_file (const char * filename)
read the contents of a file.
filename can absolute or relative, according to the fopen implementation.
Parameters
filename [in] string to the file.
Returns
a malloc'd buffer pointer or NULL on errors.
Referenced by poclu_load_program_multidev().
poclu_show_program_build_log()
POCLU_API cl_int POCLU_CALL poclu_show_program_build_log (cl_program program)
print program build log of each device to stderr.
Parameters
program [in] program of which to print build logs.
Returns
CL_SUCCESS or else a CL related error.
poclu_write_file()
POCLU_API int POCLU_CALL poclu_write_file (const char * filename, char * content, size_t size)
write content to a file.
filename can absolute or relative, according to the fopen implementation on system.
Parameters
filename [in] string to the file.
content [in] string to be written.
size [in] size of the content.
Returns
-1 if there is any error otherwise 0.